# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c14e7efa03b5719f5675a5277b32e556e027c03d07ead561f00cd5dfef81da932b60dc76ffb02e1b5ab230a06c306425228e194484303d26c90b92dd43ade74

test:
  secret_key_base: 5e84576a5b2de3f15ff838117d0ef199dbca35a417ce4c810b7467083429870d65c820ab5942ed4002e75fcba5259fe1d28f61c5cd14d5508a618d764fb87d5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
